#!/bin/bash
# config.sh - Shared configuration for Agent Swarm scripts
# All scripts should: source "$(dirname "$0")/config.sh"

# Ensure common tool paths are available (cron/tmux may have minimal PATH)
# Extra paths configurable via registry.json config.extraPath or SWARM_EXTRA_PATH env
_EXTRA_PATH="${SWARM_EXTRA_PATH:-$(jq -r '.config.extraPath // empty' "${SWARM_DIR:-${HOME}/agent-swarm}/registry.json" 2>/dev/null)}"
_EXTRA_PATH="${_EXTRA_PATH:-$HOME/.local/bin}"
# Expand $HOME and ~ in extraPath
_EXTRA_PATH="${_EXTRA_PATH//\$HOME/$HOME}"
_EXTRA_PATH="${_EXTRA_PATH/#\~/$HOME}"
export PATH="${_EXTRA_PATH}:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

SWARM_DIR="${SWARM_DIR:-${HOME}/agent-swarm}"
REGISTRY="${SWARM_DIR}/registry.json"
TASKS_FILE="${SWARM_DIR}/tasks.json"
SCRIPTS_DIR="${SWARM_DIR}/scripts"
LOGS_DIR="${SWARM_DIR}/logs"

mkdir -p "$LOGS_DIR"

# ─── Read config from registry.json ──────────────────────────────────────────
_cfg() { jq -r --arg k "$1" '.config[$k] // empty' "$REGISTRY" 2>/dev/null; }

SWARM_GIT_PROVIDER="${SWARM_GIT_PROVIDER:-$(_cfg gitProvider)}"
SWARM_GIT_PROVIDER="${SWARM_GIT_PROVIDER:-gitlab}"

SWARM_GIT_USER="${SWARM_GIT_USER:-$(_cfg gitUser)}"

SWARM_CODING_AGENT="${SWARM_CODING_AGENT:-$(_cfg codingAgent)}"
SWARM_CODING_AGENT="${SWARM_CODING_AGENT:-claude}"

SWARM_REVIEW_AGENT="${SWARM_REVIEW_AGENT:-$(_cfg reviewAgent)}"
SWARM_REVIEW_AGENT="${SWARM_REVIEW_AGENT:-codex}"

SWARM_NOTIFY_METHOD="${SWARM_NOTIFY_METHOD:-$(_cfg notifyMethod)}"
SWARM_NOTIFY_METHOD="${SWARM_NOTIFY_METHOD:-openclaw}"

SWARM_NOTIFY_TARGET="${SWARM_NOTIFY_TARGET:-$(_cfg notifyTarget)}"
SWARM_NOTIFY_CHANNEL="${SWARM_NOTIFY_CHANNEL:-$(_cfg notifyChannel)}"
SWARM_NOTIFY_CHANNEL="${SWARM_NOTIFY_CHANNEL:-telegram}"

SWARM_OBSIDIAN_DIR="${SWARM_OBSIDIAN_DIR:-$(_cfg obsidianDir)}"
SWARM_OBSIDIAN_DIR="${SWARM_OBSIDIAN_DIR/#\~/$HOME}"

SWARM_WORKTREE_BASE="${SWARM_WORKTREE_BASE:-$(_cfg worktreeBase)}"
SWARM_WORKTREE_BASE="${SWARM_WORKTREE_BASE/#\~/$HOME}"
SWARM_WORKTREE_BASE="${SWARM_WORKTREE_BASE:-${HOME}/GitLab/worktrees}"

SWARM_REPO_BASE="${SWARM_REPO_BASE:-$(_cfg repoBase)}"
SWARM_REPO_BASE="${SWARM_REPO_BASE/#\~/$HOME}"
SWARM_REPO_BASE="${SWARM_REPO_BASE:-${HOME}/GitLab/repos}"

# ─── Git provider helpers ────────────────────────────────────────────────────
swarm_mr_create() {
    local title="$1" desc_file="$2" branch="$3"
    case "$SWARM_GIT_PROVIDER" in
        gitlab)
            # Use temp file approach to avoid shell escaping issues with description content
            glab mr create --title "$title" \
                --description "$(cat "$desc_file" 2>/dev/null || echo 'Auto-generated by Agent Swarm')" \
                --source-branch "$branch" --target-branch main --yes 2>&1
            ;;
        github)
            gh pr create --title "$title" \
                --body-file "$desc_file" \
                --head "$branch" 2>&1
            ;;
    esac
}

swarm_mr_list_by_branch() {
    local branch="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab) glab mr list --source-branch "$branch" --output json 2>/dev/null ;;
        github) gh pr list --head "$branch" --json url 2>/dev/null ;;
    esac
}

swarm_mr_view() {
    local iid="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab) glab mr view "$iid" --output json 2>/dev/null ;;
        github) gh pr view "$iid" --json state,headRefName,url,statusCheckRollup 2>/dev/null ;;
    esac
}

swarm_mr_merge() {
    local iid="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab) glab mr merge "$iid" --yes --remove-source-branch --auto-merge=false ;;
        github) gh pr merge "$iid" --merge --delete-branch ;;
    esac
}

swarm_mr_url() {
    local output="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab)
            echo "$output" | grep -Eo 'https://gitlab.com/[^ ]+/-/merge_requests/[0-9]+' | head -1
            ;;
        github)
            echo "$output" | grep -Eo 'https://github.com/[^ ]+/pull/[0-9]+' | head -1
            ;;
    esac
}

swarm_mr_state() {
    local json="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab) echo "$json" | jq -r '.state // ""' 2>/dev/null ;;
        github) echo "$json" | jq -r '.state // ""' 2>/dev/null ;;
    esac
}

swarm_mr_iid_from_url() {
    local url="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab) echo "$url" | sed -n 's#.*merge_requests/\([0-9][0-9]*\).*#\1#p' ;;
        github) echo "$url" | sed -n 's#.*pull/\([0-9][0-9]*\).*#\1#p' ;;
    esac
}

swarm_repo_create() {
    local name="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab)
            glab repo view "${SWARM_GIT_USER}/${name}" &>/dev/null || \
                glab repo create "$name" --private --description "Auto-created by Agent Swarm"
            ;;
        github)
            gh repo view "${SWARM_GIT_USER}/${name}" &>/dev/null || \
                gh repo create "${SWARM_GIT_USER}/${name}" --private --description "Auto-created by Agent Swarm"
            ;;
    esac
}

swarm_repo_url() {
    local name="$1"
    case "$SWARM_GIT_PROVIDER" in
        gitlab) echo "git@gitlab.com:${SWARM_GIT_USER}/${name}.git" ;;
        github) echo "git@github.com:${SWARM_GIT_USER}/${name}.git" ;;
    esac
}

# ─── Coding agent helper ─────────────────────────────────────────────────────
swarm_run_coding_agent() {
    local prompt="$1" log_file="$2"
    case "$SWARM_CODING_AGENT" in
        claude)
            claude --dangerously-skip-permissions -p "$prompt" 2>&1 | tee -a "$log_file"
            ;;
        codex)
            echo "$prompt" | codex exec --dangerously-bypass-approvals-and-sandbox - 2>&1 | tee -a "$log_file"
            ;;
        aider)
            aider --yes --message "$prompt" 2>&1 | tee -a "$log_file"
            ;;
    esac
}

# ─── Review agent helper ─────────────────────────────────────────────────────
swarm_run_review() {
    local prompt_file="$1"
    case "$SWARM_REVIEW_AGENT" in
        codex)
            cat "$prompt_file" | codex exec review \
                --dangerously-bypass-approvals-and-sandbox \
                -c "model_reasoning_effort=high" - 2>&1
            ;;
        claude)
            claude --dangerously-skip-permissions -p "$(cat "$prompt_file")" 2>&1
            ;;
        none)
            echo "REVIEW_RESULT: PASS"
            echo "(review skipped)"
            ;;
    esac
}

# ─── Notification helper ─────────────────────────────────────────────────────
swarm_notify() {
    local msg="$1"
    case "$SWARM_NOTIFY_METHOD" in
        openclaw)
            openclaw message send --channel "$SWARM_NOTIFY_CHANNEL" \
                --target "$SWARM_NOTIFY_TARGET" --message "$msg" >/dev/null 2>&1
            ;;
        webhook)
            curl -s -X POST "$SWARM_NOTIFY_TARGET" \
                -H "Content-Type: application/json" \
                -d "{\"text\": $(echo "$msg" | jq -Rs .)}" >/dev/null 2>&1
            ;;
        none)
            return 0
            ;;
    esac
}
